#!/bin/bash
set -euo pipefail

# shellcheck disable=SC2034
declare -r CREATE_PR_VERSION="0.9.0"

CREATE_PR_ROOT_DIR="$(dirname "${BASH_SOURCE[0]}")"
export CREATE_PR_ROOT_DIR

source "$CREATE_PR_ROOT_DIR/src/dev/dumper.sh"
source "$CREATE_PR_ROOT_DIR/src/helpers.sh"
source "$CREATE_PR_ROOT_DIR/src/validate.sh"
source "$CREATE_PR_ROOT_DIR/src/pr_ticket.sh"
source "$CREATE_PR_ROOT_DIR/src/pr_body.sh"
source "$CREATE_PR_ROOT_DIR/src/pr_label.sh"
source "$CREATE_PR_ROOT_DIR/src/pr_title.sh"
source "$CREATE_PR_ROOT_DIR/src/env_configuration.sh"
source "$CREATE_PR_ROOT_DIR/src/console_header.sh"
source "$CREATE_PR_ROOT_DIR/src/main.sh"

DRY_RUN=${DRY_RUN:-false}
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  argument="$1"
  case $argument in
    --debug)
      set -x
      ;;
    --dry-run)
      DRY_RUN=true
      ;;
    -e|--env)
      # shellcheck disable=SC1090
      source "$2"
      shift
      ;;
    -t|--title)
      helpers::generate_branch_name "$2" "${3:-}"
      trap '' EXIT && exit 0
      ;;
    -h|--help)
      console_header::print_help
      trap '' EXIT && exit 0
      ;;
    -v|--version)
      console_header::print_version
      trap '' EXIT && exit 0
      ;;
    *)
      EXTRA_ARGS+=("$argument")
  esac
  shift
done

PR_LABEL=${PR_LABEL:-${LABEL:-$(pr_label "$CURRENT_BRANCH" "${PR_LABEL_MAPPING:-}")}}
PR_TITLE=$(pr_title "$CURRENT_BRANCH")
PR_BODY=$(pr_body "$CURRENT_BRANCH" "$PR_TEMPLATE")

if [[ "$DRY_RUN" == true ]]; then
  if [ ${#EXTRA_ARGS[@]} -gt 0 ]; then
    printf "EXTRA_ARGS: %s\n" "${EXTRA_ARGS[@]}"
  else
    printf "EXTRA_ARGS: empty\n"
  fi
  printf "REMOTE_URL: %s\n" "$REMOTE_URL"
  printf "TARGET_BRANCH: %s\n" "$TARGET_BRANCH"
  printf "CURRENT_BRANCH: %s\n" "$CURRENT_BRANCH"
  printf "PR_USING_CLIENT: %s\n" "$PR_USING_CLIENT"
  printf "PR_TEMPLATE: %s\n" "$PR_TEMPLATE"
  printf "PR_LABEL: %s\n" "$PR_LABEL"
  printf "PR_TITLE: %s\n" "$PR_TITLE"
  printf "PR_BODY:\n%s\n" "$PR_BODY"
  exit 0
fi

export PR_LABEL
export PR_TITLE
export PR_BODY

main::create_pr

echo "Script finished successfully."
