name: Editorconfig Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    name: "Run Lint on ${{ matrix.os }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Editorconfig Linter
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run Linter
        run: editorconfig-checker

